spring.application.name=officehub-v1

spring.datasource.url=jdbc:postgresql://localhost:5432/sgsp
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


app.security.jwt.secret=OfficeHub-JWT-Secret-Key-Minimo-32-Caracteres-Para-HS256
app.security.jwt.expiration-minutes=60
app.security.refresh-token.expiration-days=7


app.security.rate-limit.login-per-minute=10

ia.motor=${IA_MOTOR:OPENROUTER}
ia.openrouter.api-key=${OPENROUTER_API_KEY:}
ia.openrouter.base-url=${OPENROUTER_BASE_URL:https://openrouter.ai/api/v1/chat/completions}
ia.openrouter.model=google/gemini-2.5-flash
ia.openrouter.max-tokens=${OPENROUTER_MAX_TOKENS:2000}
ia.openrouter.http-referer=http://localhost
ia.openrouter.title=OfficeHub
