spring.application.name=officehub-v1

spring.datasource.url=jdbc:postgresql://localhost:5432/sgsp
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


app.security.jwt.secret=OfficeHub-JWT-Secret-Key-Minimo-32-Caracteres-Para-HS256
app.security.jwt.expiration-minutes=60
app.security.refresh-token.expiration-days=7


app.security.rate-limit.login-per-minute=10
